# -*- coding: utf-8 -*-
"""fake-news-notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGaWBPzY0e0XM_oBqdZNuXe0p251C8HZ

# Fake News Detection

**Topic:** Text classification using ML and DL
**Dataset:** Fake and Real News Dataset (Kaggle) [https://www.kaggle.com/code/rajatkumar30/fake-news-prediction-92-5-accuracy/input]

In this project I want to build a model that can classify news articles as Real or Fake.
I will compare 3 machine learning models and 3 deep learning models, then pick the best one.

## 1. Setup
"""

!pip install -q kaggle wordcloud keras-tuner

# Imports
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, learning_curve, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Bidirectional, Dropout, GlobalAveragePooling1D, Input
from tensorflow.keras.callbacks import EarlyStopping

import warnings
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

print('TensorFlow version:', tf.__version__)

"""## 2. Download Dataset

"""

if not (os.path.exists('Fake.csv') and os.path.exists('True.csv')):
    from google.colab import files
    print('Please upload kaggle.json')
    files.upload()
    !mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
    !kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset --unzip

print('Fake.csv size:', os.path.getsize('Fake.csv') / 1e6, 'MB')
print('True.csv size:', os.path.getsize('True.csv') / 1e6, 'MB')

"""## 3. Load the Data"""

fake = pd.read_csv('Fake.csv')
real = pd.read_csv('True.csv')

print('Fake shape:', fake.shape)
print('Real shape:', real.shape)
print()
print('Columns:', fake.columns.tolist())

fake['label'] = 1
real['label'] = 0

df = pd.concat([fake, real], ignore_index=True)

df = df.sample(frac=1, random_state=SEED).reset_index(drop=True)

print('Total articles:', len(df))
df.head()

print('Missing values:')
print(df.isnull().sum())
print()
print('Duplicate rows:', df.duplicated().sum())

"""## 4. Exploratory Data Analysis (EDA)

### 4.1 How many fake vs real articles?
"""

df['label'].value_counts().plot(kind='bar', color=['green', 'red'])
plt.title('Number of Real vs Fake Articles')
plt.xlabel('Label (0=Real, 1=Fake)')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()

print(df['label'].value_counts())

"""The classes are pretty balanced — fake news is slightly more (52%).

### 4.2 What subjects are in the data?
"""

# Plot subject vs label
plt.figure(figsize=(11, 4))
sns.countplot(data=df, x='subject', hue='label', order=df['subject'].value_counts().index)
plt.xticks(rotation=30)
plt.title('Subject Distribution')
plt.show()

# Crosstab to see exact numbers
print(pd.crosstab(df['subject'], df['label']))

"""Real news only have 2 subjects (`politicsNews`, `worldnews`), and fake news have completely different subjects. So the `subject` column is a giveaway — if I include it as a feature, the model just learns to look up the subject and gets 100%.

I'll drop the `subject` column and only use the article text.

### 4.3 How long are the articles?
"""

# Length analysis
df['text_length'] = df['text'].str.len()

# Plot histograms
plt.figure(figsize=(10, 4))
plt.hist(df[df['label']==0]['text_length'], bins=50, alpha=0.5, label='Real', color='green', range=(0, 15000))
plt.hist(df[df['label']==1]['text_length'], bins=50, alpha=0.5, label='Fake', color='red', range=(0, 15000))
plt.xlabel('Article length (characters)')
plt.ylabel('Count')
plt.title('Article Length Distribution')
plt.legend()
plt.show()

# Stats
print('Real articles - average length:', df[df['label']==0]['text_length'].mean())
print('Fake articles - average length:', df[df['label']==1]['text_length'].mean())

"""Lengths are roughly the same on average. The distributions overlap a lot, so length alone isn't enough.

### 4.4 Looking at sample articles
"""

# Print one real and one fake article
print('=== REAL article ===')
print(df[df['label']==0].iloc[0]['text'][:300])
print()
print('=== FAKE article ===')
print(df[df['label']==1].iloc[0]['text'][:300])

"""The real news starts with `TEHRAN (Reuters) -`. If I look at more real news, they almost all start with `(Reuters)`. This is a huge signal that's basically cheating — the model would just learn "if it has (Reuters), it's real."

I'll remove the `(Reuters)` text in preprocessing.

## 5. Cleaning the Text
"""

# Combine title and text
df['content'] = df['title'].astype(str) + ' ' + df['text'].astype(str)

# Cleaning function
stop_words = set(ENGLISH_STOP_WORDS)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\(reuters\)\s*-?\s*', ' ', text)  # remove Reuters tag
    text = re.sub(r'http\S+|www\.\S+', ' ', text)      # remove URLs
    text = re.sub(r'@\w+', ' ', text)                    # remove @mentions
    text = re.sub(r'[^a-z\s]', ' ', text)                # keep only letters
    text = re.sub(r'\s+', ' ', text).strip()             # remove extra spaces
    # Remove stop words and very short words
    words = [w for w in text.split() if w not in stop_words and len(w) > 2]
    return ' '.join(words)

print('Cleaning text... this takes about 1 minute')
df['clean'] = df['content'].apply(clean_text)

print('Done cleaning')

# Drop rows that are too short or duplicates
print('Before:', len(df))

df = df[df['clean'].str.len() > 5]
df = df.drop_duplicates(subset=['clean']).reset_index(drop=True)

print('After:', len(df))
print('Real:', (df['label']==0).sum())
print('Fake:', (df['label']==1).sum())

# Look at a cleaned sample
print('\nSample cleaned text:')
print(df['clean'].iloc[0][:200])

"""### 5.1 Most common words in each class"""

# Get all words for each class
real_words = ' '.join(df[df['label']==0]['clean']).split()
fake_words = ' '.join(df[df['label']==1]['clean']).split()

# Get top 20
real_top = Counter(real_words).most_common(20)
fake_top = Counter(fake_words).most_common(20)

# Plot
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

words, counts = zip(*real_top)
axes[0].barh(words[::-1], counts[::-1], color='green')
axes[0].set_title('Top 20 words - REAL')

words, counts = zip(*fake_top)
axes[1].barh(words[::-1], counts[::-1], color='red')
axes[1].set_title('Top 20 words - FAKE')

plt.tight_layout()
plt.show()

"""### 5.2 Word Cloud"""

# Make word clouds for each class
real_text = ' '.join(df[df['label']==0]['clean'])
fake_text = ' '.join(df[df['label']==1]['clean'])

wc_real = WordCloud(width=900, height=450, background_color='white', colormap='Greens', max_words=150, random_state=SEED).generate(real_text)
wc_fake = WordCloud(width=900, height=450, background_color='white', colormap='Reds', max_words=150, random_state=SEED).generate(fake_text)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
axes[0].imshow(wc_real)
axes[0].axis('off')
axes[0].set_title('REAL News')
axes[1].imshow(wc_fake)
axes[1].axis('off')
axes[1].set_title('FAKE News')
plt.show()

"""Real news has more institutional words (`government`, `washington`, `president`). Fake news has more personalized words (`trump`, `obama`, `clinton`).

## 6. Train-Test Split and Features
"""

# Get features (X) and labels (y)
X = df['clean'].values
y = df['label'].values

# Also keep subject info for later (for diagnostics)
subjects = df['subject'].values

# 80/20 split with stratify (to keep class balance)
X_train, X_test, y_train, y_test, subj_train, subj_test = train_test_split(
    X, y, subjects, test_size=0.2, random_state=SEED, stratify=y
)

print('Train:', len(X_train))
print('Test:', len(X_test))

# Make TF-IDF features for ML models
tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df=3, max_df=0.9)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print('TF-IDF shape:', X_train_tfidf.shape)

# Make tokenized sequences for DL models
MAX_VOCAB = 15000
MAX_LEN = 250

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token='<UNK>')
tokenizer.fit_on_texts(X_train)

X_train_seq = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=MAX_LEN, padding='post')
X_test_seq = pad_sequences(tokenizer.texts_to_sequences(X_test), maxlen=MAX_LEN, padding='post')

print('Sequence shape:', X_train_seq.shape)

"""## 7. Machine Learning Models

"""

results = []

def show_results(name, y_true, y_pred, y_score):
    """Helper to print metrics and store them"""
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    auc = roc_auc_score(y_true, y_score)

    print(f'{name}')
    print(f'  Accuracy:  {acc:.4f}')
    print(f'  Precision: {prec:.4f}')
    print(f'  Recall:    {rec:.4f}')
    print(f'  F1:        {f1:.4f}')
    print(f'  ROC-AUC:   {auc:.4f}')

    results.append({
        'Model': name, 'Accuracy': acc, 'Precision': prec,
        'Recall': rec, 'F1': f1, 'ROC_AUC': auc
    })

# Model 1: Logistic Regression
lr = LogisticRegression(max_iter=1000, n_jobs=-1)
lr.fit(X_train_tfidf, y_train)

pred_lr = lr.predict(X_test_tfidf)
score_lr = lr.predict_proba(X_test_tfidf)[:, 1]

show_results('Logistic Regression', y_test, pred_lr, score_lr)

# Model 2: Multinomial Naive Bayes
nb = MultinomialNB(alpha=0.1)
nb.fit(X_train_tfidf, y_train)

pred_nb = nb.predict(X_test_tfidf)
score_nb = nb.predict_proba(X_test_tfidf)[:, 1]

show_results('Multinomial Naive Bayes', y_test, pred_nb, score_nb)

# Model 3: Passive Aggressive Classifier
pac = PassiveAggressiveClassifier(max_iter=1000, random_state=SEED)
pac.fit(X_train_tfidf, y_train)

pred_pac = pac.predict(X_test_tfidf)
# PAC doesn't have predict_proba so use decision_function instead
score_pac = pac.decision_function(X_test_tfidf)

show_results('Passive Aggressive', y_test, pred_pac, score_pac)

"""## 8. Deep Learning Models

"""

# Use early stopping to prevent overfitting
early_stop = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

VOCAB_SIZE = MAX_VOCAB
EMB_DIM = 64

# Model 4: Dense Neural Network
model_dense = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(VOCAB_SIZE, EMB_DIM),
    GlobalAveragePooling1D(),
    Dense(64, activation='relu'),
    Dropout(0.4),
    Dense(1, activation='sigmoid')
])

model_dense.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
hist_dense = model_dense.fit(X_train_seq, y_train, epochs=3, batch_size=128,
                              validation_split=0.1, callbacks=[early_stop], verbose=1)

# Predict on test
score_dense = model_dense.predict(X_test_seq, verbose=0).ravel()
pred_dense = (score_dense >= 0.5).astype(int)

show_results('Dense Neural Network', y_test, pred_dense, score_dense)

# Model 5: LSTM
model_lstm = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(VOCAB_SIZE, EMB_DIM),
    LSTM(48, dropout=0.3),
    Dense(32, activation='relu'),
    Dropout(0.4),
    Dense(1, activation='sigmoid')
])

model_lstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
hist_lstm = model_lstm.fit(X_train_seq, y_train, epochs=2, batch_size=128,
                            validation_split=0.1, callbacks=[early_stop], verbose=1)

score_lstm = model_lstm.predict(X_test_seq, verbose=0).ravel()
pred_lstm = (score_lstm >= 0.5).astype(int)

show_results('LSTM', y_test, pred_lstm, score_lstm)

# Model 6: Bidirectional LSTM
model_bilstm = Sequential([
    Input(shape=(MAX_LEN,)),
    Embedding(VOCAB_SIZE, EMB_DIM),
    Bidirectional(LSTM(48, dropout=0.3)),
    Dense(32, activation='relu'),
    Dropout(0.4),
    Dense(1, activation='sigmoid')
])

model_bilstm.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
hist_bilstm = model_bilstm.fit(X_train_seq, y_train, epochs=2, batch_size=128,
                                validation_split=0.1, callbacks=[early_stop], verbose=1)

score_bilstm = model_bilstm.predict(X_test_seq, verbose=0).ravel()
pred_bilstm = (score_bilstm >= 0.5).astype(int)

show_results('Bidirectional LSTM', y_test, pred_bilstm, score_bilstm)

"""### Plot DL training history"""

# Plot accuracy and loss curves for the 3 DL models
fig, axes = plt.subplots(2, 3, figsize=(14, 6))

for col, (name, hist) in enumerate([('Dense', hist_dense), ('LSTM', hist_lstm), ('BiLSTM', hist_bilstm)]):
    axes[0][col].plot(hist.history['accuracy'], label='train', marker='o')
    axes[0][col].plot(hist.history['val_accuracy'], label='val', marker='s')
    axes[0][col].set_title(f'{name} - accuracy')
    axes[0][col].legend()
    axes[0][col].grid(True)

    axes[1][col].plot(hist.history['loss'], label='train', marker='o')
    axes[1][col].plot(hist.history['val_loss'], label='val', marker='s')
    axes[1][col].set_title(f'{name} - loss')
    axes[1][col].legend()
    axes[1][col].grid(True)

plt.tight_layout()
plt.show()

"""## 9. Comparing All Models"""

# Make a leaderboard
results_df = pd.DataFrame(results)
results_df = results_df.sort_values('F1', ascending=False).reset_index(drop=True)
print('LEADERBOARD (sorted by F1):')
print(results_df.round(4).to_string(index=False))

# Bar chart comparison
ax = results_df.set_index('Model')[['Accuracy', 'Precision', 'Recall', 'F1', 'ROC_AUC']].plot(
    kind='bar', figsize=(12, 5), colormap='viridis'
)
ax.set_title('Model Comparison')
ax.set_ylim(0.75, 1.01)
ax.set_xticklabels(ax.get_xticklabels(), rotation=15, ha='right')
ax.legend(loc='lower right')
plt.tight_layout()
plt.show()

# Pick the best model based on F1
best_model_name = results_df.iloc[0]['Model']
print('Best model:', best_model_name)
print('F1 score:', round(results_df.iloc[0]['F1'], 4))

"""### Confusion Matrix of Best Model"""

# Get predictions from the best model: Passive Agressive
best_pred = pred_pac

cm = confusion_matrix(y_test, best_pred)
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
plt.title(f'Confusion Matrix - {best_model_name}')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

print('Classification Report:')
print(classification_report(y_test, best_pred, target_names=['Real', 'Fake']))

"""### ROC Curves for All Models"""

# Plot ROC curves
plt.figure(figsize=(7, 6))

for name, score in [('Logistic Regression', score_lr),
                    ('Naive Bayes', score_nb),
                    ('Passive Aggressive', score_pac),
                    ('Dense NN', score_dense),
                    ('LSTM', score_lstm),
                    ('BiLSTM', score_bilstm)]:
    fpr, tpr, _ = roc_curve(y_test, score)
    auc = roc_auc_score(y_test, score)
    plt.plot(fpr, tpr, label=f'{name} (AUC={auc:.3f})')

plt.plot([0, 1], [0, 1], '--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves')
plt.legend(loc='lower right')
plt.show()

"""## 9.5 Diagnostics — Is the Model Really Good?

The F1 scores are very high (0.98+). Let me check:
1. Is the model overfitting? (Compare train vs test)
2. Does it underfit? (Learning curve)
3. Are these numbers stable? (Cross-validation)
4. Is it learning a shortcut? (Per-subject + adversarial test)
5. What words is it using? (Feature importance)

The best model is **Passive Aggressive** with F1 = 0.9860, but I need to verify before trusting it.

### 9.5.1 Train vs Test gap (overfitting check)
"""

# Check train accuracy vs test accuracy for each model
print('Train vs Test gap (high gap = overfitting):')
print()

# ML models
for name, model in [('Logistic Regression', lr), ('Multinomial Naive Bayes', nb), ('Passive Aggressive', pac)]:
    train_acc = accuracy_score(y_train, model.predict(X_train_tfidf))
    test_acc = accuracy_score(y_test, model.predict(X_test_tfidf))
    gap = train_acc - test_acc
    print(f'   {name:>23s}    {train_acc:.4f}    {test_acc:.4f}    {gap:+.4f}')

# DL models
for name, model in [('Dense Neural Network', model_dense), ('LSTM', model_lstm), ('Bidirectional LSTM', model_bilstm)]:
    train_pred = (model.predict(X_train_seq, verbose=0).ravel() >= 0.5).astype(int)
    test_pred = (model.predict(X_test_seq, verbose=0).ravel() >= 0.5).astype(int)
    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)
    gap = train_acc - test_acc
    print(f'   {name:>23s}    {train_acc:.4f}    {test_acc:.4f}    {gap:+.4f}')

"""All gaps are below 1.5%. No overfitting problem.

### 9.5.2 Learning Curve
"""

# Learning curve for Logistic Regression

train_sizes, train_scores, val_scores = learning_curve(
    LogisticRegression(max_iter=1000, n_jobs=-1),
    X_train_tfidf, y_train,
    train_sizes=np.linspace(0.1, 1.0, 5),
    cv=3, scoring='accuracy', n_jobs=-1, random_state=SEED
)

train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)

plt.figure(figsize=(9, 5))
plt.plot(train_sizes, train_mean, 'o-', label='Training', color='blue')
plt.plot(train_sizes, val_mean, 'o-', label='Validation', color='orange')
plt.xlabel('Training samples')
plt.ylabel('Accuracy')
plt.title('Learning Curve - Logistic Regression')
plt.legend()
plt.grid(True)
plt.show()

"""Both curves go up and converge near each other — no underfit, no overfit, just a good fit.

### 9.5.3 5-Fold Cross-Validation
"""

# Run 5-fold CV on the full data
print('Running 5-fold CV... (this takes a few minutes)')

# Need to fit TF-IDF on full data for this
tfidf_full = TfidfVectorizer(max_features=20000, ngram_range=(1,2), min_df=3, max_df=0.9)
X_all_tfidf = tfidf_full.fit_transform(X)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

cv_scores = {}
for name, model in [('Logistic Regression', LogisticRegression(max_iter=1000, n_jobs=-1)),
                    ('Multinomial NB', MultinomialNB(alpha=0.1)),
                    ('Passive Aggressive', PassiveAggressiveClassifier(max_iter=1000, random_state=SEED))]:
    scores = cross_val_score(model, X_all_tfidf, y, cv=skf, scoring='f1', n_jobs=-1)
    cv_scores[name] = scores
    print(f'{name}: F1 mean = {scores.mean():.4f}, std = {scores.std():.4f}')

# Boxplot of CV scores
plt.figure(figsize=(9, 4))
plt.boxplot(list(cv_scores.values()), tick_labels=list(cv_scores.keys()))
plt.ylabel('F1 score')
plt.title('5-Fold CV F1 Distribution')
plt.grid(axis='y')
plt.show()

"""Standard deviations are tiny (<0.005). The numbers are stable.

### 9.5.4 Per-Subject Accuracy
"""

# Check accuracy per subject - does the model work equally well across topics?
subj_df = pd.DataFrame({
    'subject': subj_test,
    'true': y_test,
    'pred': best_pred
})

per_subj = subj_df.groupby('subject').apply(
    lambda g: pd.Series({
        'n': len(g),
        'accuracy': accuracy_score(g['true'], g['pred'])
    })
).round(4)

print(per_subj)

per_subj['accuracy'].sort_values().plot(kind='barh', figsize=(11, 4), color='purple')
plt.title(f'Accuracy per Subject - {best_model_name}')
plt.xlim(0.85, 1.005)
plt.show()

"""Lowest is Government News at 92.5%, the rest are 96%+. Reasonably consistent.

### 9.5.5 Adversarial Test
"""

# Remove Reuters-style words from test set
style_words = ['reuters', 'said', 'told', 'spokesman', 'spokeswoman', 'official']

def remove_style_words(text):
    return ' '.join(w for w in text.split() if w not in style_words)

X_test_adv = np.array([remove_style_words(t) for t in X_test])
X_test_adv_tfidf = tfidf.transform(X_test_adv)
X_test_adv_seq = pad_sequences(tokenizer.texts_to_sequences(X_test_adv), maxlen=MAX_LEN, padding='post')

print('Comparing original vs adversarial accuracy:')
print()
print('Model                     Original    Adversarial    Drop')

for name, model, vec_data in [('Logistic Regression', lr, (X_test_tfidf, X_test_adv_tfidf)),
                               ('Multinomial NB', nb, (X_test_tfidf, X_test_adv_tfidf)),
                               ('Passive Aggressive', pac, (X_test_tfidf, X_test_adv_tfidf))]:
    acc_orig = accuracy_score(y_test, model.predict(vec_data[0]))
    acc_adv = accuracy_score(y_test, model.predict(vec_data[1]))
    print(f'{name:<20s}      {acc_orig:.4f}        {acc_adv:.4f}    {acc_orig-acc_adv:+.4f}')

for name, model in [('Dense NN', model_dense), ('LSTM', model_lstm), ('BiLSTM', model_bilstm)]:
    pred_orig = (model.predict(X_test_seq, verbose=0).ravel() >= 0.5).astype(int)
    pred_adv = (model.predict(X_test_adv_seq, verbose=0).ravel() >= 0.5).astype(int)
    acc_orig = accuracy_score(y_test, pred_orig)
    acc_adv = accuracy_score(y_test, pred_adv)
    print(f'{name:<20s}      {acc_orig:.4f}        {acc_adv:.4f}    {acc_orig-acc_adv:+.4f}')

"""- ML models drop only 0.7-1.2% — they're robust
- DL models drop 4.6-9.2% — they rely much more on those style words

So the DL models are more fragile if we use them on news from sources outside Reuters.

### 9.5.6 What Words Did the Model Learn?
"""

# Show top 25 words pushing toward FAKE and toward REAL (from Logistic Regression)
words = np.array(tfidf.get_feature_names_out())
coefs = lr.coef_[0]

top_fake = np.argsort(coefs)[-25:][::-1]
top_real = np.argsort(coefs)[:25]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
axes[0].barh(words[top_fake][::-1], coefs[top_fake][::-1], color='red')
axes[0].set_title('Top 25 - words indicating FAKE')

axes[1].barh(words[top_real][::-1], coefs[top_real][::-1], color='green')
axes[1].set_title('Top 25 - words indicating REAL')

plt.tight_layout()
plt.show()

"""## 9.6 Hyperparameter Tuning

"""

# Tune Logistic Regression
print('Tuning Logistic Regression...')
grid_lr = GridSearchCV(LogisticRegression(max_iter=1000),
                       {'C': [0.5, 1.0, 5.0]},
                       cv=3, scoring='f1', n_jobs=-1)
grid_lr.fit(X_train_tfidf, y_train)
print('Best params:', grid_lr.best_params_)
print('Best CV F1:', round(grid_lr.best_score_, 4))
print('Test F1 (tuned):', round(f1_score(y_test, grid_lr.predict(X_test_tfidf)), 4))
print()

# Tune Naive Bayes
print('Tuning Naive Bayes...')
grid_nb = GridSearchCV(MultinomialNB(),
                       {'alpha': [0.01, 0.1, 0.5, 1.0]},
                       cv=3, scoring='f1', n_jobs=-1)
grid_nb.fit(X_train_tfidf, y_train)
print('Best params:', grid_nb.best_params_)
print('Best CV F1:', round(grid_nb.best_score_, 4))
print('Test F1 (tuned):', round(f1_score(y_test, grid_nb.predict(X_test_tfidf)), 4))
print()

# Tune Passive Aggressive
print('Tuning Passive Aggressive...')
grid_pac = GridSearchCV(PassiveAggressiveClassifier(max_iter=1000, random_state=SEED),
                        {'C': [0.1, 0.5, 1.0, 2.0]},
                        cv=3, scoring='f1', n_jobs=-1)
grid_pac.fit(X_train_tfidf, y_train)
print('Best params:', grid_pac.best_params_)
print('Best CV F1:', round(grid_pac.best_score_, 4))
print('Test F1 (tuned):', round(f1_score(y_test, grid_pac.predict(X_test_tfidf)), 4))

# Default vs Tuned comparison
print('Comparing default vs tuned:')
print()
print('Model                  Default    Tuned     Improvement')
print(f'Logistic Regression    0.9772    0.9828    +0.0057')
print(f'Naive Bayes            0.9458    0.9491    +0.0033')
print(f'Passive Aggressive     0.9860    0.9860    +0.0000')

"""Tuning only gave very small improvements (less than 0.6%). My default settings were already pretty good.

## 10. Sample Predictions on Test Articles
"""

# Try the best model on a few real test articles
test_samples = []
real_idx = np.where(y_test == 0)[0][:2]
fake_idx = np.where(y_test == 1)[0][:2]

for idx in list(real_idx) + list(fake_idx):
    test_samples.append((y_test[idx], X_test[idx]))

for i, (label, text) in enumerate(test_samples, 1):
    label_name = 'Real' if label == 0 else 'Fake'

    # Predict using each model
    vec = tfidf.transform([text])
    seq = pad_sequences(tokenizer.texts_to_sequences([text]), maxlen=MAX_LEN, padding='post')

    p_lr = lr.predict_proba(vec)[0, 1]
    p_nb = nb.predict_proba(vec)[0, 1]
    p_bilstm = float(model_bilstm.predict(seq, verbose=0).ravel()[0])

    print(f'\n--- Sample {i} ---')
    print(f'True label: {label_name}')
    print(f'Text preview: {text[:120]}...')
    print(f'LR prob_fake = {p_lr:.4f}, NB = {p_nb:.4f}, BiLSTM = {p_bilstm:.4f}')

"""## 10.5 Predict on New News Articles

The previous section was just evaluating on test articles where I already know the answer. Now lets actually use the model to predict on new text.
"""

# Function to predict on any new text
def predict_news(text):
    # Step 1: clean the text the same way as training
    cleaned = clean_text(text)

    # Step 2: turn into features for ML and DL
    vec = tfidf.transform([cleaned])
    seq = pad_sequences(tokenizer.texts_to_sequences([cleaned]), maxlen=MAX_LEN, padding='post')

    # Step 3: get predictions from 3 models
    p_lr = lr.predict_proba(vec)[0, 1]
    p_nb = nb.predict_proba(vec)[0, 1]
    p_bilstm = float(model_bilstm.predict(seq, verbose=0).ravel()[0])

    # Step 4: average the 3 (simple ensemble)
    p_avg = (p_lr + p_nb + p_bilstm) / 3
    verdict = 'FAKE' if p_avg >= 0.5 else 'REAL'

    print(f'Article preview: {text[:100].strip()}...')
    print(f'  Logistic Regression: {p_lr:.4f}')
    print(f'  Naive Bayes:         {p_nb:.4f}')
    print(f'  BiLSTM:              {p_bilstm:.4f}')
    print(f'  Average:             {p_avg:.4f}')
    print(f'  >>> Verdict: {verdict} <<<')

# Try it on a Real-style article
news1 = '''
WASHINGTON - The Federal Reserve raised its benchmark interest rate by a quarter
percentage point on Wednesday, citing continued strength in the labor market and
inflation that remains above the central bank's 2 percent target. The decision was
unanimous among voting members of the Federal Open Market Committee.
'''
predict_news(news1)

# Try it on a Fake-style article
news2 = '''
SHOCKING! You won't BELIEVE what this politician just admitted on live television!
The mainstream media is hiding this from you, but we have the EXCLUSIVE footage that
proves everything they've been saying is a complete LIE. Patriots everywhere are
sharing this story before it gets censored.
'''
predict_news(news2)

"""## 11. Conclusion

### What I did
- Loaded 44,898 news articles, ended up with 38,823 unique ones after cleaning
- Found and fixed two data leakage problems:
  - The `(Reuters)` tag at the start of real articles → removed in preprocessing
  - The `subject` column had no overlap between Real and Fake → dropped before training
- Trained 6 models (3 ML + 3 DL) and compared them
- Did diagnostics to make sure the model is actually good
- Tuned hyperparameters and added a way to predict on new articles

### Final results

| Model | F1 Score |
|---|---|
| **Passive Aggressive** | **0.9860** ← winner |
| Bidirectional LSTM | 0.9773 |
| Logistic Regression | 0.9772 |
| Dense Neural Network | 0.9487 |
| Multinomial Naive Bayes | 0.9458 |
| LSTM | 0.8248 |

### Things I learned
1. **High accuracy isn't always a good thing.** F1 ≈ 0.99 sounds amazing but it actually made me suspicious. The diagnostics confirmed that part of this performance comes from style/source patterns, not from understanding what's actually true.
2. **Simpler ML models beat DL here.** Passive Aggressive (a simple linear model) beat all 3 DL models. With ~31k samples and a strong word-frequency signal, deep learning didn't add much value.
3. **DL models are more fragile to style changes.** When I removed Reuters-style words, accuracy dropped 4-9% for DL models but only 1% for ML models.
4. **Hyperparameter tuning had small effect.** The defaults were already near-optimal — I gained less than 0.6% from tuning.

### Limitations (being honest)
- 0.98 F1 is only valid for this dataset. On news from other sources, performance will probably drop a lot.
- The model learns writing style more than facts. So it's not a true "fake news detector" — more like a "Reuters-style vs alternative-style classifier."
- Only works in English.
- Topic bias: mostly Trump-era US politics from 2016-2017.


"""